development:
  site: bquadrant 
  use_ssl: true
  rooms:
  - Discussion
  api_key: 6918bed72d6c50a0a02dc20dbac6c47957f24b6e
  nickname: Ruby
  fullname: Ruby
  enable_plugins: 
    - echo
production:
  site: bquadrant
  use_ssl: true
  rooms:
  - Discussion
  api_key: 6918bed72d6c50a0a02dc20dbac6c47957f24b6e
  nickname: Ruby
  fullname: Ruby
  enable_plugins: 
    - echo